# 创建Tensor

In [1]:
import torch

创建一个5*3的未初始化的Tensor

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[-2.4773e+27,  2.0697e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


创建一2个5*3的随机初始化的Tensor

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.9344, 0.0494, 0.7964],
        [0.6983, 0.1218, 0.0757],
        [0.4907, 0.8961, 0.1031],
        [0.9850, 0.5103, 0.6336],
        [0.2758, 0.1022, 0.7983]])


创建一个5*3的long型全0的Tensor

In [9]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


根据现有的数据创建tensor

In [16]:
x = torch.tensor([[5.5,3],[6.8,9.8]])
print(x)
print(x[0][1])

tensor([[5.5000, 3.0000],
        [6.8000, 9.8000]])
tensor(3.)


根据现有的tensor来创建，会默认使用一些原有数据的属性，如数据类型，除非是自定义的

In [18]:
x = x.new_ones(1,1)
print(x)

tensor([[1.]])


In [23]:
x = torch.randn_like(x,dtype = torch.float64)
print(x)

tensor([[0.2084]], dtype=torch.float64)


获得tensor的形状

In [26]:
print(x.shape)

torch.Size([1, 1])


In [28]:
print(x.size())

torch.Size([1, 1])


# 算数操作

In [1]:
import torch

加法形式一

In [2]:
x = torch.zeros(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
print(torch.exp(x))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [4]:
y = torch.rand(5,3)
print(y)
print(x+y)

tensor([[0.0419, 0.4291, 0.2660],
        [0.3619, 0.6151, 0.2311],
        [0.1060, 0.9407, 0.4304],
        [0.5925, 0.1019, 0.6672],
        [0.5731, 0.1996, 0.9875]])
tensor([[0.0419, 0.4291, 0.2660],
        [0.3619, 0.6151, 0.2311],
        [0.1060, 0.9407, 0.4304],
        [0.5925, 0.1019, 0.6672],
        [0.5731, 0.1996, 0.9875]])


加法形式二

In [5]:
print(x.add(y))

tensor([[0.0419, 0.4291, 0.2660],
        [0.3619, 0.6151, 0.2311],
        [0.1060, 0.9407, 0.4304],
        [0.5925, 0.1019, 0.6672],
        [0.5731, 0.1996, 0.9875]])


In [6]:
#指定输出：
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.0419, 0.4291, 0.2660],
        [0.3619, 0.6151, 0.2311],
        [0.1060, 0.9407, 0.4304],
        [0.5925, 0.1019, 0.6672],
        [0.5731, 0.1996, 0.9875]])


加法形式三、inplace

In [38]:
y.add_(x)

tensor([[0.1929, 0.7544, 0.1040],
        [0.4818, 0.7699, 0.4030],
        [0.4992, 0.0424, 0.7787],
        [0.5341, 0.4032, 0.1206],
        [0.9327, 0.9625, 0.4446]])

# 索引

！！！可以使用索引来访问tensor的一部分
注意：索引出来的结果与源数据共享内存，即修改一个，另外一个也会被修改

In [41]:
x=torch.rand(5,3)
print(x)

tensor([[0.4690, 0.6588, 0.0163],
        [0.9910, 0.7227, 0.1732],
        [0.4709, 0.5933, 0.7618],
        [0.4013, 0.5198, 0.2606],
        [0.8867, 0.9374, 0.2577]])


In [42]:
# 获取第一行的所有数据
x[0]

tensor([0.4690, 0.6588, 0.0163])

In [47]:
# 逗号后为列号的索引，因为列没有索引所以获得第0行的所有看列
x[0,]

tensor(0.6588)

In [52]:
#逗号后为列号索引：进行切片操作，从：前的第几个元素开始到不包含：后的第几个元素
x[0,1:2]

tensor([0.6588])

# 获得列数据

In [53]:
#注意python语法中不允许第一个索引为空，使用：即可获得这一列所有数据
#获取第二列数据
x[:,1]

tensor([0.6588, 0.7227, 0.5933, 0.5198, 0.9374])

In [55]:
x[1:,1]
y = x+1
print(y)

tensor([[1.4690, 1.6588, 1.0163],
        [1.9910, 1.7227, 1.1732],
        [1.4709, 1.5933, 1.7618],
        [1.4013, 1.5198, 1.2606],
        [1.8867, 1.9374, 1.2577]])


# 改变形状

In [6]:
import torch
x = torch.rand(2,2)
print(x)

tensor([[0.3045, 0.7497],
        [0.1472, 0.8742]])


In [13]:
# 获得一个一维的tensor,!!维度要相同

y = x.view(4)
print(y)
y= x.view(-1)
print(y)

tensor([0.3045, 0.7497, 0.1472, 0.8742])
tensor([0.3045, 0.7497, 0.1472, 0.8742])


In [14]:
y = x.view(1,4)
print(y)

tensor([[0.3045, 0.7497, 0.1472, 0.8742]])


In [15]:
#-1表示该维度取决于其它维度的大小
z = x.view(2,-1)
print(z)

tensor([[0.3045, 0.7497],
        [0.1472, 0.8742]])


In [1]:
#！！注意view()返回的tensor与原tensor虽然有不同的size，但是也是会共享data
#，更改其中的一个，另外一个也会随之改变，view()仅仅改变了观察数据的角度，
# 内部数据并未改变
# ！！同时注意虽然view返回的tensor与原来的tensor是共享data的
#，但依旧是一个全新的tensor，因为tensor包含一些data之外的属性，二者的id并不一致

In [17]:
x = torch.rand(3,3)
print(x)

tensor([[0.2425, 0.5884, 0.5308],
        [0.6920, 0.5309, 0.1933],
        [0.9324, 0.0767, 0.0485]])


In [21]:
y = x.view(-1)
y.shape

torch.Size([9])

In [27]:
y[1]+=1
print(y)
print(x)

tensor([0.2425, 1.5884, 0.5308, 0.6920, 0.5309, 0.1933, 0.9324, 0.0767, 0.0485])
tensor([[0.2425, 1.5884, 0.5308],
        [0.6920, 0.5309, 0.1933],
        [0.9324, 0.0767, 0.0485]])


In [31]:
# 使用clone()产生一个副本
x_cp = x.clone()
x_cp

tensor([[0.2425, 1.5884, 0.5308],
        [0.6920, 0.5309, 0.1933],
        [0.9324, 0.0767, 0.0485]])

In [32]:
x_cp[0,0]+=1
print(x)
print(x_cp)

tensor([[0.2425, 1.5884, 0.5308],
        [0.6920, 0.5309, 0.1933],
        [0.9324, 0.0767, 0.0485]])
tensor([[1.2425, 1.5884, 0.5308],
        [0.6920, 0.5309, 0.1933],
        [0.9324, 0.0767, 0.0485]])


In [35]:
# arange产生0-3的数据，不包含4torch.arange(start, end, step=1, 
#dtype=None, layout=torch.strided,
#device=None, requires_grad=False) -> Tensor
x=torch.arange(4)
print(x)

tensor([0, 1, 2, 3])


# 广播机制

In [3]:
import torch
x = torch.arange(1,3).view(1,2)
print(x)

tensor([[1, 2]])


In [4]:
y = torch.arange(1,4).view(3,1)
print(y)

tensor([[1],
        [2],
        [3]])


In [5]:
# 计算时x的一行二列被广播为3行二列
# y被广播为三行，二列
print(x+y)

tensor([[2, 3],
        [3, 4],
        [4, 5]])


# 运算的内存开销

In [6]:
import torch

In [7]:
#索引操作是不会开辟内存的，但像y= y+x这样的操作是会开辟新内存的，
# 然后将y指向新内存，用python自带的id函数，如果两个实例的id一致
#，那么他们对应的内存地址相同

In [8]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
print(x)

tensor([1, 2])


In [12]:
id_before = id(y)

In [13]:
y = y+x

In [14]:
print(id(y)==id_before)

False


In [4]:
#如果想指定结果到原来的y内存，可以使用索引来进行替换操作，如把x+y的结果通过[:]
#写进y对应的内存中
import torch
x =torch.tensor([[1,2],[3,4]])
print(x)


tensor([[1, 2],
        [3, 4]])


In [5]:
y = torch.zeros(2,2)
print(y)

tensor([[0., 0.],
        [0., 0.]])


In [9]:
id1 = id(y)
y[:,:] = y+x
print(y)
if id1 == id(y):
    print('yes')

tensor([[ 4.,  8.],
        [12., 16.]])
yes


In [10]:
#还可以通过运算符全名函数中的out参数或者自加运算符+=达到相同结果
# torch.add(x,y,out=y)
#y+=x

# numpy和tensor的转换

In [13]:
# tensor转换成numpy
a = torch.ones(5)
b= a.numpy()
print(a,b)
a+=1
print(a,b)
b+=1
print(a,b)
#!!使用numpy()转换后numpy数组和tensor共享内存

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [17]:
# numpy数组转换成tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [18]:
#此外上面提到还有一个常用的方法就是直接用torch.tensor()
#将NumPy数组转换成Tensor，需要注意的是该方法总是会进行数据拷贝，
#返回的Tensor和原来的数据不再共享内存。
c = torch.tensor(a)
a+=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [19]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型


tensor([[2, 3],
        [4, 5]], device='cuda:0')
tensor([[2., 3.],
        [4., 5.]], dtype=torch.float64)


In [8]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [10]:
print(X)
print(Y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


In [15]:
# 对两个张量按行进行连接
tem = torch.cat((X,Y),dim = 0)
print(tem)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


In [16]:
tem = torch.cat((X,Y),dim = 1)
print(tem)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [17]:
# 对应位置是否相等
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
# 对所有的张量进行求和，得到一个新的张量
X.sum()

tensor(66.)

In [22]:
X = torch.arange(12).reshape(3,4)

In [23]:
Y = torch.zeros(3,4)

In [24]:
X == Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [25]:
X<Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
X>Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [28]:
Z = torch.arange(8).reshape(2,2,2)
print(Z)

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])


In [46]:
a = torch.arange(4).reshape(2,2,1)

In [47]:
print(a)

tensor([[[0],
         [1]],

        [[2],
         [3]]])


In [48]:
a + Z

tensor([[[ 0,  1],
         [ 3,  4]],

        [[ 6,  7],
         [ 9, 10]]])

# 数据预处理

In [1]:
#写入csv数据
import os

os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [2]:
import pandas as pd

In [3]:
#利用pandas读取数据
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [6]:
# 处理缺失项 data.iloc[行切片row_indices, 列切片column_indices]
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs['NumRooms'].fillna(inputs['NumRooms'].mean(),inplace=True)
print(inputs)


   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [5]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [79]:
import torch
x = torch.tensor(inputs.to_numpy(dtype = float))
y = torch.tensor(outputs.to_numpy(dtype = float))

In [80]:
print(x)
print(y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)


# 线性代数

In [19]:
import torch
a = torch.arange(20).reshape(4,5)

In [21]:
# 矩阵和矩阵的转置
print(a)
print(a.T)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])


## 张量

In [23]:
# 向量是一阶张量
# 矩阵是二阶张量
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [29]:
# 求和函数的使用 A.sum(axis = 0) 按行降维 1按列
# A.sum(axis=[0, 1])  # 结果和A.sum()相同
A.sum()

tensor(190.)

In [30]:
# 计算平均值
A.mean()# 直接求平均值
A.sum()/A.numel()#和除以元素个数

tensor(9.5000)

In [31]:
#同样，计算平均值的函数也可以沿指定轴降低张量的维度
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [34]:
# keeppdims表示轴数不变
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [35]:
# 对行进行累计和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [38]:
# 元素的点积 对应位置相乘 a1*b1+a2*b2+a3*b3
import torch
y = torch.ones(4,dtype= torch.float32)
x = torch.arange(4,dtype = torch.float32)
torch.dot(x,y)

tensor(6.)

In [39]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [40]:
print(A)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [41]:
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 范数

In [42]:
# 向量范数是将向量映射到标量的函数f
# 性质一：如果我们按常数因子缩放所有元素，
# 其范数也会按相同的常数因子的绝对值缩放 f(ax)=|a|f(x)

In [43]:
# 性质二：满足三角不等式
# f(x+ y)<=f(x)+f(y)

In [44]:
# 性质三：范数大于等于0
#性质四：范数最小为0，当且仅当向量全由0组成

In [47]:
#L2范数
#向量中的所有元素的平方和再开平方
u = torch.tensor([3.0,-4.0])
print(torch.norm(u))
# L1范数
# 向量中元素的绝对值之和
print(torch.abs(u).sum())

tensor(5.)
tensor(7.)


In [49]:
# 矩阵的L2范数
torch.norm(torch.ones((4, 9)))

tensor(6.)

# 微积分

In [53]:
%matplotlib inline
import numpy as np
from matplotlib_inline import backend_inline
from d2l import torch as d2l


def f(x):
    return 3 * x ** 2 - 4 * x
def numerical_lim(f, x, h):
    return (f(x + h) - f(x)) / h

h = 0.1
for i in range(5):
    print(f'h={h:.5f}, numerical limit={numerical_lim(f, 1, h):.5f}')
    h *= 0.1

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


# 自动微分

In [30]:
import torch

In [31]:
x = torch.arange(4.0,requires_grad=True)
print(x.grad)

None


In [32]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [33]:
x.grad

In [34]:
y = x.sum()
y.backward()
y.backward()
x.grad

tensor([2., 2., 2., 2.])

In [25]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad == d/a

tensor(True)