# PyTorch基本操作实验

## 一、Pytorch基本操作考察

### 1、使用 𝐓𝐞𝐧𝐬𝐨𝐫 初始化一个 𝟏×𝟑 的矩阵 𝑴 和一个 𝟐×𝟏 的矩阵 𝑵，对两矩阵进行减法操作（要求实现三种不同的形式），给出结果并分析三种方式的不同（如果出现报错，分析报错的原因），同时需要指出在计算过程中发生了什么

In [33]:
import torch
M = torch.tensor([1,2,3])
N = torch.tensor([[1],[1]])

In [34]:
# 方式一：直接相减
res1 = M - N
print("方式一结果:",'\n',res1)
# PyTorch启用广播机制，它自动调整N的形状以匹配M的形状。在这里，N被复制并扩展成2x3的矩阵
# M被扩展成2x3矩阵然后进行相减

方式一结果: 
 tensor([[0, 1, 2],
        [0, 1, 2]])


In [35]:
# 方式二：torch.sub进行
res2 = M.sub(N)
print("方式二结果:",'\n',res2)
# 方式二同样也利用了广播机制，与直接相减方式相同

方式二结果: 
 tensor([[0, 1, 2],
        [0, 1, 2]])


In [36]:
# 方式三：inplace函数
import torch
M = torch.tensor([1,2,3])
N = torch.tensor([[1],[1]])
res3 = M.sub_(N)
print("方式三结果:",'\n',res3)
# 由于广播机制会扩大张量M的在一维和二维上的长度，与inplace原地操作不兼容，所以会报错

RuntimeError: output with shape [3] doesn't match the broadcast shape [2, 3]

### 2、① 利用 𝐓𝐞𝐧𝐬𝐨𝐫 创建两个大小分别 𝟑×𝟐 和 𝟒×𝟐 的随机数矩阵 𝑷 和 𝑸 ，要求服从均值为0，标准差0.01为的正态分布；② 对第二步得到的矩阵 𝑸 进行形状变换得到 𝑸 的转置 𝑸^𝑻 ；③ 对上述得到的矩阵 𝑷 和矩阵 𝑸^𝑻 求矩阵相乘

In [38]:
# 问题1解答：
import torch
P = torch.normal(0,0.01,(3,2))
Q = torch.normal(0,0.01,(4,2))
print(P,'\n',Q)

tensor([[ 0.0074, -0.0048],
        [-0.0020, -0.0115],
        [ 0.0093, -0.0224]]) 
 tensor([[ 7.8963e-03, -2.2350e-03],
        [ 2.6952e-03,  2.3349e-02],
        [-9.6502e-05,  1.4392e-02],
        [-6.8178e-04, -7.6675e-04]])


In [41]:
# 问题二解答：获得Q的转置
Q = Q.T
print(Q)

tensor([[ 7.8963e-03,  2.6952e-03, -9.6502e-05, -6.8178e-04],
        [-2.2350e-03,  2.3349e-02,  1.4392e-02, -7.6675e-04]])


In [50]:
# 问题三解答：矩阵相乘
torch.mm(P,Q)

tensor([[ 6.9028e-05, -9.2042e-05, -6.9715e-05, -1.3586e-06],
        [ 9.6982e-06, -2.7486e-04, -1.6584e-04,  1.0235e-05],
        [ 1.2397e-04, -4.9866e-04, -3.2380e-04,  1.0828e-05]])

### 3、给定公式 𝑦_3=𝑦_1+𝑦_2=𝑥^2+𝑥^3，且 𝑥=1。利用学习所得到的Tensor的相关知识，求𝑦_3对𝑥的梯度，即(𝑑𝑦_3)/𝑑𝑥。要求在计算过程中，在计算〖 𝑥〗^3 时中断梯度的追踪，观察结果并进行原因分析 提示, 可使用 with torch.no_grad()， 举例: with torch.no_grad(): y = x * 5

In [59]:
x = torch.tensor(1,dtype=torch.float64,requires_grad=True)

In [61]:
y1=x*x
y2=x*x*x
y3=y1+y2
y3.backward()
print(x.grad)

tensor(5., dtype=torch.float64)


## 二、动手实现 logistic 回归

### 1、要求动手从0实现 logistic 回归（只借助Tensor和Numpy相关的库）在人工构造的数据集上进行训练和测试，并从loss以及训练集上的准确率等多个角度对结果进行分析（可借助nn.BCELoss或nn.BCEWithLogitsLoss作为损失函数，从零实现二元交叉熵为选作）